### ISSUE TITLE
Release without package manager?

### ISSUE THREAD

**Issue by jbergstroem** [bitnami/bitnami-docker-node#122]
I'd like to see a release without package managers such as yarn and npm. This is a good practice for more than one reason:
1. Size (the obvious one): it is my understanding that one goal of the "minideb" ecosystem is to achieve a smaller size. Adding both `npm` and `yarn` (where the user would opt for one) makes sense from a usability point of view but goes against the "only include what you need" rule.
2. Security: `npm run $foo` is usually a plethora of bash and javascript nowadays. forcing users to invoke `node index.js` (read: no npm available) is a security benefit.

The best practice coupled with this would be to have a build phase that installs production dependencies followed by a `COPY --from=builder` into the `npm/yarn`-less image.

**Comment by carrodher** [comment]
All our images are based on minideb a minimalist Debian based container image which gives you a small base container image and the familiarity of a leading linux distribution, but we need to find a balance between size and functionality.
We already created the `-prod` tags in order to avoid development deps: https://github.com/bitnami/bitnami-docker-node#what-are-prod-tagged-containers-for

Related to the package manager, some weeks ago we received a request from some users asking us to include `yarn` (https://github.com/bitnami/bitnami-docker-node/issues/117) and we did it, so it seems the community prefers to include those kinds of packages. Anyway, I will create an internal task to discuss it.

Thanks!

**Comment by jbergstroem** [comment]
Thanks for the response!

> We already created the -prod tags in order to avoid development deps

Yeah, I guess the semantics of what a node "production" environment should contain could be thought about.

> so it seems the community prefers to include those kinds of packages.

Would `pnpm` also fit in there if there was a request to add it? I guess I'm just trying to explore what guidelines are more important; size/conventions or developer friendliness (or where the compromise lies).

**Comment by carrodher** [comment]
Hi, thanks again for the suggestions, we try to implement our users' requests taking into account different variables like the effort needed to apply those changes, the increase of size in the image, if it is aligned with our ideas, the reception/support of the proposal by other community members, etc

In this case, if there is a strong support to make the change we could study it, but AFAIK `npm` is included by default in the node tarball, also `yarn` was requested by some users and there is not a huge increase in the size as to remove it.

**Comment by Fydon** [comment]
@carrodher The `-prod` tags seem to have been dropped around 24 January. Was there a reason for this?

**Comment by carrodher** [comment]
Yes, the `-prod` tags were removed at https://github.com/bitnami/bitnami-docker-node/commit/e3ea33935a07cee43b04c2b48430a1171beef647 at the [beginning of the year](https://github.com/bitnami/bitnami-docker-ruby#deprecation-note-2022-01-21).

The reason behind that is that we had a prod tag (`-prod`) in some containers images: python, php, node, ruby, and java.

*What was this `-prod` tag?* We were releasing two images for every branch supported, i.e in the case of Java we have `1.8`, `11`, and `17`; but also `1.8-prod}`, `11-prod` and `17-prod`.

*What was the difference between the regular image and the prod one?* In terms of bits, those are the differences (i.e java 17):
```diff
diff -r 17/debian-10/Dockerfile 17-prod/debian-10/Dockerfile
- RUN install_packages acl ca-certificates curl gzip libc6 libsqlite3-dev libssl-dev locales procps tar wget zlib1g
+ RUN install_packages acl ca-certificates curl gzip libc6 locales procps tar zlib1g
-     BITNAMI_IMAGE_VERSION="17.0.1-debian-10-r82" \
+     BITNAMI_IMAGE_VERSION="17.0.1-prod-debian-10-r81" \
```
so, in this specific case, both images are the same but the `17-prod` does NOT contain some packages: `libsqlite3-dev`, `libssl-dev`, and `wget`

In terms of size, this is translated to
```console
$ docker images
REPOSITORY                                         TAG                 IMAGE ID       CREATED        SIZE
bitnami/java                                       17-prod             069204a39ef2   45 hours ago   473MB
bitnami/java                                       17                  98dfc4691c50   45 hours ago   513MB
```

Originally, we created the prod containers in order to have a version without an internal tool called _nami_ (nami being based on node.js forced us to add a lot of extra tools). The moment we got rid of nami in favor of bash containers, the prod containers stopped making sense, being the removal of some system packages the only difference.
